### ISSUE TITLE
Have espec run specs in umbrella apps?

### ISSUE THREAD

**Issue by s0urpuss** [antonmi/espec#187]
I'm having quite the time getting espec to run specs in my umbrella app's sub-directories.

I've updated my `mix.exs` files to point to the correct places, and added the following lines to my umbrella application's `mix.exs`, and it doesn't ever run my tests:

```
def project do
...
  spec_pattern: ["*_spec.exs"],
  spec_paths: ["apps/app_name/spec/"]
...
end

```

And I've added these lines to my sub-app's `mix.esx`:

```
def project do
...
  spec_pattern: ["*_spec.exs", "spec_helper.exs"],
  spec_paths: ["spec/"],
...
```

Does anything jump out at you?

**Comment by antonmi** [comment]
Hi, @s0urpuss !
Thanks for trying espec!

Seems like you missed 
```elixir
preferred_cli_env: [espec: :test]
```
I've also prepared a demo project for you:
[https://github.com/antonmi/umbrella_with_espec](https://github.com/antonmi/umbrella_with_espec)

So, you should add espec to the dependencies in global mix file and
```elixir
preferred_cli_env: [espec: :test]
```

You needn't specify `spec_pattern` and `spec_path` because they have default values: "*_spec.exs" and ["spec"].

Then you are able to run the specs from the root folder for all the projects in apps folder.

If you wanna run specs inside specific project, you need to add espec into its dependency (and `preferred_cli_env` too). See 'umbrella_with_espec/apps/pr_espec/mix.exs'.

**Comment by s0urpuss** [comment]
Yeah, it was my fault. I've figured it out!

**Comment by zachdaniel** [comment]
In addition to this, I've noticed that when specifying a path, you can't use the relative path from the root of the umbrella app.  Basically, if you say `mix espec apps/my_app/spec/apps/bar_spec.exs`, it won't work, but just `spec/apps/bar_spec.exs` and the full path both work.  I wonder if a special case could be added to remove the apps/my_app prefix, or some other concession could be made?
