### ISSUE TITLE
Make let/let!/subject public

### ISSUE THREAD

**Issue by tomciopp** [antonmi/espec#204]
I often want to debug within my specs by popping in an `IEx.pry` statement within a test. When I do this I want to be able to inspect all of variables/functions that I have defined. Currently I cannot do this due to the fact that all of the `lets` are private, so when I want to view them I get an `UndefinedFunctionError`.

For example if I try to see what response contains in this example using `pry` I will get an error.

    require IEx
    let(:response) do
        build_conn()
        |> get(page_path(build_conn, :index))
      end

    it "returns a 200 status" do 
      IEx.pry # call response() get (UndefinedFunctionError)
      expect(repsonse().status).to eq(200)
    end

Unless I am mistaken, I believe the only thing that needs to change is to switch `do_let` from `defp` to `def` for this functionality to work.

**Comment by antonmi** [comment]
Hi, @tomciopp !
Thanks for using ESpec.
You can't access the function directly because IEx.pry does not put you in the scope of the module being pried. You need to call the function with module name (the spec module in your case).

More details:
[http://stackoverflow.com/questions/37106555/elixir-pry-cannot-execute-private-methods](http://stackoverflow.com/questions/37106555/elixir-pry-cannot-execute-private-methods)
[https://hexdocs.pm/iex/IEx.html#pry/1](https://hexdocs.pm/iex/IEx.html#pry/1)

**Comment by tomciopp** [comment]
@antonmi Thank you for the clarification! It is now obvious what I was doing wrong.
