### ISSUE TITLE
Pattern matching: Improve formatting for MatchErrors

### ISSUE THREAD

**Issue by Zeeker** [antonmi/espec#232]
When doing pattern matching in ExUnit via the match operator (`=`), a failed match will be nicely formatted in the following fashion:

#### Without `assert`

![ExUnit - MatchErrror without assert](https://user-images.githubusercontent.com/2647626/30149292-63a317a4-93a7-11e7-9751-b249341884be.png)

#### Using `assert`

![ExUnit - MatchError using assert](https://user-images.githubusercontent.com/2647626/30149346-95450dda-93a7-11e7-8119-2ad35feeb503.png)

---

ESpec on the other hand does not handle `MatchError`s in any special way, so a failed match will look like this:

![ESpec - MatchError](https://user-images.githubusercontent.com/2647626/30149152-db722460-93a6-11e7-9913-2f3ede1ef20b.png)

IMO ESpec provides a great deal of information for failed tests, often being superior to ExUnit in that regard. As such I think this would be a useful extension and improve the testing experience.

**Comment by Zeeker** [comment]
I'm happy to submit a pull request but not sure where to start on this issue. Can somebody point me in the right direction?

**Comment by antonmi** [comment]
Hi @Zeeker !
I suppose you mean code like:
```elixir
assert {:ok, 1} = {:ok, 2}
```
It is quite tricky in espec, because under the hood 'assert' is just 'BeTruthy' assertion.
So the expression above is the same as:
```elixir
expect({:ok, 1} = {:ok, 2}).to be_truthy
```
To handle the case you mentioned we need to implemet 'assert' (and 'refute') in different way.

So, to help you start, take a look:
- `lib/espec/assert.ex`
- `lib/espec/assertions/boolean/be_truthy.ex`
- `lib/espec/assertion_helpers.ex`

And, of courcse, take a look at the 'assert' implementation in `ExUnit`
https://github.com/elixir-lang/elixir/blob/v1.5.1/lib/ex_unit/lib/ex_unit/assertions.ex#L161

Thank you!

**Comment by Zeeker** [comment]
I would suggest a different approach. We could add another matcher which performs pattern matching. For that we can use `Kernel.match?/2`. For a failed match a diff should suffice.

In addition I would probably extend test error handling to handle MatchErrors more gracefully to be closer to ExUnits handling.

**Comment by antonmi** [comment]
Sounds good!
Let's try it!
