### ISSUE TITLE
Leaking 'subject' issue

### ISSUE THREAD

**Issue by brain-geek** [antonmi/espec#89]
Hey!

I've been playing with ESpec and found an unexpected behaviour. This is the minimal case I could get to reproduce it:

``` Elixir
defmodule TestSpec do
  use ESpec

  describe "first" do
    subject do: []

    it "is empty by default", do: should be_empty
  end

  describe "second" do
    it "is empty too", do: should be_empty
  end
end
```

Actual result:

```
..
	2 examples, 0 failures

	Finished in 0.42 seconds (0.39s on load, 0.03s on specs)

	Randomized with seed 907520
```

Expected result:

```
F.

	1) TestSpec TestSpec second is empty too
	spec/test_spec.exs:11
	** (CaseClauseError) no case clause matching: nil

	2 examples, 1 failures

	Finished in 0.49 seconds (0.45s on load, 0.04s on specs)

	Randomized with seed 63815
```

**Comment by jonathanperret** [comment]
Note that you can hit the same error if you try to use a `let` binding outside of a context where it is defined. The error is expected, since your `subject` has no binding in your second context.

I agree though that the error message could be clearer. Furthermore, I think that with the current implementation, whether you hit that error or incorrectly obtain a leaked value of `subject` is dependent on test execution order, which is unfortunate. But I want to stress that the test is incorrect in any case.

**Comment by brain-geek** [comment]
Yes, the spec is incorrect, but there are two key things I'd want to focus in this issue:
- When subject hasn't been set - message should be self-explanatory
- Sometimes subject leaks to other contexts, which should not be happening

**Comment by antonmi** [comment]
Hi, Alex!
This is known issue caused by ESpec 'let' implementation.

Just how it works in few words:
When you use 'let', 'let!' or 'subject' macros ESpec defines the function inside the spec module. 
Once you call that function ESpec stores the return value in the Agent.
If you redefine 'let' in the inner context, ESpec rewrites the cached value.

So, the 'subject' function is defined in the spec module. And you can access it in all the examples.

The only solution I can invent now is to store 'let' value with context when it is defined and check that context on every call. But I don't like that solution because it brings a lot of overhead to 'let' lookup.

@jonathanperret could have a better idea.
Let's discuss.

**Comment by antonmi** [comment]
I've added I check step in compilation time.
You'll see either
(ESpec.LetError) The let function `a/0` is not defined in the current scope!
or
(ESpec.LetError) The subject is not defined in the current scope!
error in compile time.
Please test.

**Comment by brain-geek** [comment]
@antonmi Can you release the new version to mix?

It would be a bit simpler to use then git.

**Comment by brain-geek** [comment]
Hey!

Looks like there is a regression:
```Elixir
    context do
    let :the_data, do: true

    context do
        context  do
          it  do
            IO.inspect the_data <- fails
```

**Comment by antonmi** [comment]
It's awesome when ESpec helps to find the bugs!:)

**Comment by antonmi** [comment]
I've published 0.8.17

**Comment by jonathanperret** [comment]
Sorry I couldn't comment earlier, @antonmi. My initial thought was to catch uninitialized `let`s at runtime but it looks like you built a static analyzer instead, which is probably better as it can catch errors earlier. I wouldn't have trusted myself to get it right though, so it's a good thing you did the work :)

**Comment by antonmi** [comment]
Thanks, @jonathanperret!

**Comment by jonathanperret** [comment]
OK, I just took the `let` checker for a spin and sadly have to report I found a case where it did not catch a bad `let` reference. Here's the spec:

```elixir
defmodule SomeSpec do
  use ESpec
  describe "second" do
    it do: expect a |> to(eq 1)
  end
  describe "first" do
    let :a, do: 1
    it do: expect a |> to(eq 1)
  end
end
```

You may notice it's the same one as `@code1` in `test/let/leaking_let_test.exs` but with the contexts reversed. Running this gets me either success, or a `no case clause matching: nil` depending on the random seed.

I haven't investigated yet why the checker failed to detect the bad reference.

**Comment by antonmi** [comment]
Thank, Jonathan!
Yes, the issue exists. @defined_lets module variable doesn't have 'a' function when AST being analyzed.
I have a solution. But it requires the runtime AST check (not good).
Will make PR soon.
